import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="border-b">
        <div className="flex justify-between pl-6 -mb-px">
          <h3 className="text-blue-800 py-4 font-semi text-xl">Home</h3>
          <div className="flex"></div>
        </div>
      </div>
      <div>
        <p>Full Name: Joe Bloggs</p>
        <p>Address: </p>
        <p>City: </p>
        <p>Postcode: </p>
        <p>N/A Number: </p>
        <p>Length of employment: </p>
      </div>
      <h1>This is home!</h1>
      <ol>
        <li>Hold payslips here?</li>
        <li>Training?</li>
        <li>Invoices</li>
        <li>Employee details</li>
        <ul>
          <li>Full Name</li>
          <li>Address</li>
          <li>Job Role</li>
          <li>Duration of employment</li>
          <li>Nation insurance number</li>
        </ul>
        <li>Accreditations/Awards?</li>
      </ol>
    </div>
  );
};

export default Home;
