import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>This is home!</h1>
      <ol>
        <li>Hold payslips here?</li>
        <li>Training?</li>
        <li>Invoices</li>
        <li>Employee details</li>
        <ul>
          <li>Full Name</li>
          <li>Address</li>
          <li>Job Role</li>
          <li>Duration of employment</li>
          <li>Nation insurance number</li>
        </ul>
        <li>Accreditations/Awards?</li>
      </ol>
    </div>
  );
};

export default Home;
