import type { NextPage } from 'next';
import Head from 'next/head';
import Calender from '../../components/Calendar/Calender';

const Holidays: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Calender />
    </div>
  );
};

export default Holidays;
