name: CI/CD

on:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install NPM deps
        run: npm ci
      - name: Build App
        run: npm run export
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_bracnh: gh-pages
          build_dir: out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
